const affi={
  "status": true,
  "data": [
      {
          "id": 1,
          "affirmation_text": "मैं अपनी mistakes को सुधार कर एक better person बन रहा हूँ।",
          "voice_one": [
              {
                  "id": 115,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "7d1ad4e3-995b-4036-ac1a-ae98cf412b23",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:01:14.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/115/MeApniMisteksKo.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/115/MeApniMisteksKo.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 116,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "af46e0a9-3621-4f0b-b529-5333d608be8c",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:01:14.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/116/MeApniMisteksKo.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/116/MeApniMisteksKo.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 117,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "8d7bebca-7293-4424-9bad-7210bfdde8f4",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:01:21.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/117/MeApniMisteksKo.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/117/MeApniMisteksKo.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 118,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "e0859f5a-8185-4d69-9e79-4d31e8576de2",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:01:25.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/118/MeApniMisteksKo.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/118/MeApniMisteksKo.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-03-21 10:51:57",
          "updated_at": "2024-05-29 07:01:59",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 1,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 115,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "7d1ad4e3-995b-4036-ac1a-ae98cf412b23",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:01:14.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/115/MeApniMisteksKo.mp3",
                  "preview_url": ""
              },
              {
                  "id": 116,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "af46e0a9-3621-4f0b-b529-5333d608be8c",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:01:14.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/116/MeApniMisteksKo.mp3",
                  "preview_url": ""
              },
              {
                  "id": 117,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "8d7bebca-7293-4424-9bad-7210bfdde8f4",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:01:21.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/117/MeApniMisteksKo.mp3",
                  "preview_url": ""
              },
              {
                  "id": 118,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 1,
                  "uuid": "e0859f5a-8185-4d69-9e79-4d31e8576de2",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeApniMisteksKo",
                  "file_name": "MeApniMisteksKo.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 79245,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:01:25.000000Z",
                  "updated_at": "2024-05-29T07:01:59.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/118/MeApniMisteksKo.mp3",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 2,
          "affirmation_text": "मुझे मेरी self-worth पता है और मैं उसे accept करता हूँ।",
          "voice_one": [
              {
                  "id": 119,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "5f0251c3-818a-4030-a65c-cfa4125ced18",
                  "collection_name": "affirmation_voice_one",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:08:24.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/119/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/119/MujheMeriSelfWorthPataHai.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 120,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "759780b7-9a1c-4347-9c1d-fa29a6be72a9",
                  "collection_name": "affirmation_voice_two",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:08:26.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/120/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/120/MujheMeriSelfWorthPataHai.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 121,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "46cb69a5-64f9-4dca-b1a8-f56bd7cd70ee",
                  "collection_name": "affirmation_voice_three",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:08:30.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/121/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/121/MujheMeriSelfWorthPataHai.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 122,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "b39f2d21-cd86-40a1-a7d0-8141aa861301",
                  "collection_name": "affirmation_voice_four",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:08:33.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/122/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/122/MujheMeriSelfWorthPataHai.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-03-21 10:53:05",
          "updated_at": "2024-05-29 07:08:47",
          "deleted_at": null,
          "is_favorite": true,
          "favorite_id": 2,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 2,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 119,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "5f0251c3-818a-4030-a65c-cfa4125ced18",
                  "collection_name": "affirmation_voice_one",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:08:24.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/119/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": ""
              },
              {
                  "id": 120,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "759780b7-9a1c-4347-9c1d-fa29a6be72a9",
                  "collection_name": "affirmation_voice_two",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:08:26.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/120/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": ""
              },
              {
                  "id": 121,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "46cb69a5-64f9-4dca-b1a8-f56bd7cd70ee",
                  "collection_name": "affirmation_voice_three",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:08:30.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/121/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": ""
              },
              {
                  "id": 122,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 2,
                  "uuid": "b39f2d21-cd86-40a1-a7d0-8141aa861301",
                  "collection_name": "affirmation_voice_four",
                  "name": "MujheMeriSelfWorthPataHai",
                  "file_name": "MujheMeriSelfWorthPataHai.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 80205,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:08:33.000000Z",
                  "updated_at": "2024-05-29T07:08:47.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/122/MujheMeriSelfWorthPataHai.mp3",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 3,
          "affirmation_text": "मैं खुद को without any condition स्वीकार करता हूं।",
          "voice_one": [
              {
                  "id": 123,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "172748a0-3467-47c5-b7f7-67e832f2c8a8",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:10:15.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/123/MeKhudKoWithout.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/123/MeKhudKoWithout.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 124,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "62537202-0813-42dd-a097-8d405a9726e0",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:10:20.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/124/MeKhudKoWithout.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/124/MeKhudKoWithout.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 125,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "289e1005-8b7b-4db0-9b42-c1534631d454",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:10:23.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/125/MeKhudKoWithout.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/125/MeKhudKoWithout.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 126,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "c10045e2-c815-40fe-9b6f-27802d7bbddb",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:10:27.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/126/MeKhudKoWithout.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/126/MeKhudKoWithout.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-03-21 10:53:36",
          "updated_at": "2024-05-29 07:10:41",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 3,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 123,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "172748a0-3467-47c5-b7f7-67e832f2c8a8",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:10:15.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/123/MeKhudKoWithout.mp3",
                  "preview_url": ""
              },
              {
                  "id": 124,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "62537202-0813-42dd-a097-8d405a9726e0",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:10:20.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/124/MeKhudKoWithout.mp3",
                  "preview_url": ""
              },
              {
                  "id": 125,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "289e1005-8b7b-4db0-9b42-c1534631d454",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:10:23.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/125/MeKhudKoWithout.mp3",
                  "preview_url": ""
              },
              {
                  "id": 126,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 3,
                  "uuid": "c10045e2-c815-40fe-9b6f-27802d7bbddb",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeKhudKoWithout",
                  "file_name": "MeKhudKoWithout.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 63405,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:10:27.000000Z",
                  "updated_at": "2024-05-29T07:10:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/126/MeKhudKoWithout.mp3",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 4,
          "affirmation_text": " मैं हर दिन Success के लिए कदम बड़ा रहा हूँ।",
          "voice_one": [
              {
                  "id": 127,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "1031c36f-e5af-42c7-bfac-25ae0f9564a1",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:11:33.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/127/MeHarDinSuccess.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/127/MeHarDinSuccess.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 128,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "061b1959-9163-4dc8-9f57-751d68f70287",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:11:37.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/128/MeHarDinSuccess.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/128/MeHarDinSuccess.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 129,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "44246dc8-cb12-4ff9-89c6-277544291690",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:11:46.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/129/MeHarDinSuccess.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/129/MeHarDinSuccess.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 130,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "9b437495-2a54-4222-97e6-081db17f5615",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:11:51.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/130/MeHarDinSuccess.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/130/MeHarDinSuccess.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-03-21 10:54:14",
          "updated_at": "2024-05-29 07:12:06",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 4,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 127,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "1031c36f-e5af-42c7-bfac-25ae0f9564a1",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:11:33.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/127/MeHarDinSuccess.mp3",
                  "preview_url": ""
              },
              {
                  "id": 128,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "061b1959-9163-4dc8-9f57-751d68f70287",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:11:37.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/128/MeHarDinSuccess.mp3",
                  "preview_url": ""
              },
              {
                  "id": 129,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "44246dc8-cb12-4ff9-89c6-277544291690",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:11:46.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/129/MeHarDinSuccess.mp3",
                  "preview_url": ""
              },
              {
                  "id": 130,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 4,
                  "uuid": "9b437495-2a54-4222-97e6-081db17f5615",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeHarDinSuccess",
                  "file_name": "MeHarDinSuccess.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 58125,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:11:51.000000Z",
                  "updated_at": "2024-05-29T07:12:07.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/130/MeHarDinSuccess.mp3",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 5,
          "affirmation_text": "मैं Fear की Place पर faith को चुनता हूँ।",
          "voice_one": [
              {
                  "id": 131,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "4b4fa0c2-319e-4e92-b445-d280cbc08fd4",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:12:51.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/131/MeFearKiPlaceParFaith.wav",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/131/MeFearKiPlaceParFaith.wav"
              }
          ],
          "voice_two": [
              {
                  "id": 132,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "773259ae-2bd1-4d92-913f-36b0ed64d39e",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:12:55.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/132/MeFearKiPlaceParFaith.wav",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/132/MeFearKiPlaceParFaith.wav"
              }
          ],
          "voice_three": [
              {
                  "id": 133,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "8e253195-7fbc-494e-a421-6d38c2c33b13",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:12:59.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/133/MeFearKiPlaceParFaith.wav",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/133/MeFearKiPlaceParFaith.wav"
              }
          ],
          "voice_four": [
              {
                  "id": 134,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "101e836c-8d3f-462a-88e9-4f68cc11ad87",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:13:03.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/134/MeFearKiPlaceParFaith.wav",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/134/MeFearKiPlaceParFaith.wav"
              }
          ],
          "status": "1",
          "created_at": "2024-03-21 10:57:44",
          "updated_at": "2024-05-29 07:13:13",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 5,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 131,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "4b4fa0c2-319e-4e92-b445-d280cbc08fd4",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:12:51.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/131/MeFearKiPlaceParFaith.wav",
                  "preview_url": ""
              },
              {
                  "id": 132,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "773259ae-2bd1-4d92-913f-36b0ed64d39e",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:12:55.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/132/MeFearKiPlaceParFaith.wav",
                  "preview_url": ""
              },
              {
                  "id": 133,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "8e253195-7fbc-494e-a421-6d38c2c33b13",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:12:59.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/133/MeFearKiPlaceParFaith.wav",
                  "preview_url": ""
              },
              {
                  "id": 134,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 5,
                  "uuid": "101e836c-8d3f-462a-88e9-4f68cc11ad87",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeFearKiPlaceParFaith",
                  "file_name": "MeFearKiPlaceParFaith.wav",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 10944,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:13:03.000000Z",
                  "updated_at": "2024-05-29T07:13:13.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/134/MeFearKiPlaceParFaith.wav",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 6,
          "affirmation_text": "मैं love, compassion और sympathy को deserve करता हूँ।",
          "voice_one": [
              {
                  "id": 135,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "41e107fa-e262-4ed1-bdd9-e591a8600a3d",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:16:17.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/135/MeLoveCompassion.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/135/MeLoveCompassion.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 136,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "3bbb276f-e9be-47b7-98d5-ffc498733fcd",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:16:21.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/136/MeLoveCompassion.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/136/MeLoveCompassion.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 137,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "c070e7af-1714-4368-ae48-0269c997949f",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:16:25.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/137/MeLoveCompassion.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/137/MeLoveCompassion.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 138,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "d18d7e69-dbf3-45e0-bf9d-eae3bbfa8be8",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:16:29.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/138/MeLoveCompassion.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/138/MeLoveCompassion.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-03-27 09:22:51",
          "updated_at": "2024-05-29 07:16:41",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 6,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 135,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "41e107fa-e262-4ed1-bdd9-e591a8600a3d",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:16:17.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/135/MeLoveCompassion.mp3",
                  "preview_url": ""
              },
              {
                  "id": 136,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "3bbb276f-e9be-47b7-98d5-ffc498733fcd",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:16:21.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/136/MeLoveCompassion.mp3",
                  "preview_url": ""
              },
              {
                  "id": 137,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "c070e7af-1714-4368-ae48-0269c997949f",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:16:25.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/137/MeLoveCompassion.mp3",
                  "preview_url": ""
              },
              {
                  "id": 138,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 6,
                  "uuid": "d18d7e69-dbf3-45e0-bf9d-eae3bbfa8be8",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeLoveCompassion",
                  "file_name": "MeLoveCompassion.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 69165,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:16:29.000000Z",
                  "updated_at": "2024-05-29T07:16:41.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/138/MeLoveCompassion.mp3",
                  "preview_url": ""
              }
          ]
      },
      {
          "id": 9,
          "affirmation_text": " मैंने आज तक जो कुछ भी achieve किया है उस पर मुझे Proud है।",
          "voice_one": [
              {
                  "id": 139,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "a9baebc5-9925-4bfe-9c05-826379ef2ed9",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:18:05.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/139/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/139/MeneAajTakJoKuchBhi.mp3"
              }
          ],
          "voice_two": [
              {
                  "id": 140,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "e31a900a-df35-47ca-b917-ccf7673f927f",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:18:08.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/140/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/140/MeneAajTakJoKuchBhi.mp3"
              }
          ],
          "voice_three": [
              {
                  "id": 141,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "3471cf24-951b-440f-aa3b-ec6a52949682",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:18:12.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/141/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/141/MeneAajTakJoKuchBhi.mp3"
              }
          ],
          "voice_four": [
              {
                  "id": 142,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "b8c3e975-e6ea-478d-8d7c-0de2ab15c0cc",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:18:15.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/142/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": "",
                  "url": "https://stimuli.forebearpro.co.in/storage/app/public/142/MeneAajTakJoKuchBhi.mp3"
              }
          ],
          "status": "1",
          "created_at": "2024-04-08 15:01:26",
          "updated_at": "2024-05-29 07:18:27",
          "deleted_at": null,
          "is_favorite": false,
          "favorite_id": null,
          "group": [
              {
                  "id": 5,
                  "group_name": "Personal Growth",
                  "status": "1",
                  "created_at": "2024-03-21 10:48:10",
                  "updated_at": "2024-03-21 10:48:10",
                  "deleted_at": null,
                  "pivot": {
                      "affirmation_id": 9,
                      "group_id": 5
                  }
              }
          ],
          "media": [
              {
                  "id": 139,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "a9baebc5-9925-4bfe-9c05-826379ef2ed9",
                  "collection_name": "affirmation_voice_one",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 5,
                  "created_at": "2024-05-29T07:18:05.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/139/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": ""
              },
              {
                  "id": 140,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "e31a900a-df35-47ca-b917-ccf7673f927f",
                  "collection_name": "affirmation_voice_two",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 6,
                  "created_at": "2024-05-29T07:18:08.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/140/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": ""
              },
              {
                  "id": 141,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "3471cf24-951b-440f-aa3b-ec6a52949682",
                  "collection_name": "affirmation_voice_three",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 7,
                  "created_at": "2024-05-29T07:18:12.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/141/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": ""
              },
              {
                  "id": 142,
                  "model_type": "App\\Models\\Affirmation",
                  "model_id": 9,
                  "uuid": "b8c3e975-e6ea-478d-8d7c-0de2ab15c0cc",
                  "collection_name": "affirmation_voice_four",
                  "name": "MeneAajTakJoKuchBhi",
                  "file_name": "MeneAajTakJoKuchBhi.mp3",
                  "mime_type": "audio/mpeg",
                  "disk": "public",
                  "conversions_disk": "public",
                  "size": 84045,
                  "manipulations": [],
                  "custom_properties": [],
                  "generated_conversions": [],
                  "responsive_images": [],
                  "order_column": 8,
                  "created_at": "2024-05-29T07:18:15.000000Z",
                  "updated_at": "2024-05-29T07:18:27.000000Z",
                  "original_url": "https://stimuli.forebearpro.co.in/storage/app/public/142/MeneAajTakJoKuchBhi.mp3",
                  "preview_url": ""
              }
          ]
      }
  ],
  "message": "All Affirmation are fetched successfully..",
  "errors": []
}
const playPlalist=affi.data
export default playPlalist